spring:
  application:
    name: qrpay-backend
  datasource:
    url: jdbc:h2:mem:test.db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
